packageExtensions:
  '@emotion/styled@*':
    dependencies:
      '@emotion/react': '*'
  '@storybook/addon-docs@*':
    dependencies:
      '@babel/core': '*'
  '@storybook/addons@*':
    dependencies:
      '@types/webpack-env': '*'
  '@storybook/components@*':
    dependencies:
      '@emotion/styled-base': '*'
      '@storybook/api': '*'
      regenerator-runtime: '*'
  '@storybook/core@*':
    dependencies:
      '@storybook/builder-webpack5': '*'
  '@storybook/theming@*':
    dependencies:
      '@emotion/serialize': '*'
      '@emotion/utils': '*'
  '@testing-library/react@*':
    dependencies:
      react-dom: '*'

yarnPath: .yarn/releases/yarn-0.0.1-git.20230302.hash-20c60c4a.cjs
