enableGlobalCache: false

packageExtensions:
  '@storybook/addon-docs@*':
    dependencies:
      '@babel/core': '*'
  '@storybook/addons@*':
    dependencies:
      '@types/webpack-env': '*'
  '@storybook/components@*':
    dependencies:
      '@storybook/api': '*'
      regenerator-runtime: '*'
  '@storybook/core@*':
    dependencies:
      '@storybook/builder-webpack5': '*'
  '@testing-library/react@*':
    dependencies:
      react-dom: '*'

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-remote.cjs
