packageExtensions:
  '@monstrs/mctl-ui@*':
    dependencies:
      '@monstrs/logger': '*'
  '@storybook/components@*':
    dependencies:
      regenerator-runtime: '*'
  '@ui-admin/button@*':
    dependencies:
      '@mdx-js/react': '*'
      '@storybook/addon-docs': '*'
      core-js: '*'
  '@ui-admin/theme@*':
    dependencies:
      core-js: '*'
  '@ui-parts/button@*':
    dependencies:
      '@mdx-js/react': '*'
      '@storybook/addon-docs': '*'
      core-js: '*'
  '@ui-parts/design-fonts@*':
    dependencies:
      core-js: '*'
  '@ui-parts/design@*':
    dependencies:
      '@storybook/addon-docs': '*'
  '@ui-parts/styles@*':
    dependencies:
      core-js: '*'
  '@ui-proto/button@*':
    dependencies:
      '@mdx-js/react': '*'
      '@storybook/addon-docs': '*'
      core-js: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - .yarn/plugins/plugin-patch-storybook-args.cjs

yarnPath: .yarn/releases/yarn-2.4.1.cjs
