packageExtensions:
  '@emotion/styled@*':
    dependencies:
      '@emotion/react': '*'
  '@monstrs/mctl-ui@*':
    dependencies:
      '@monstrs/logger': '*'
  '@storybook/addon-docs@*':
    dependencies:
      '@babel/core': '*'
  '@storybook/addons@*':
    dependencies:
      '@types/webpack-env': '*'
  '@storybook/components@*':
    dependencies:
      '@emotion/styled-base': '*'
      '@storybook/api': '*'
      regenerator-runtime: '*'
  '@storybook/core@*':
    dependencies:
      '@storybook/builder-webpack5': '*'
  '@storybook/theming@*':
    dependencies:
      '@emotion/serialize': '*'
      '@emotion/utils': '*'
  '@testing-library/react@*':
    dependencies:
      react-dom: '*'
  '@ui-admin/button@*':
    dependencies:
      '@mdx-js/react': '*'
      '@storybook/addon-docs': '*'
      core-js: '*'
  '@ui-admin/theme@*':
    dependencies:
      core-js: '*'
  '@ui-parts/button@*':
    dependencies:
      '@mdx-js/react': '*'
      '@storybook/addon-docs': '*'
      core-js: '*'
  '@ui-parts/design-fonts@*':
    dependencies:
      core-js: '*'
  '@ui-parts/design@*':
    dependencies:
      '@storybook/addon-docs': '*'
  '@ui-parts/styles@*':
    dependencies:
      core-js: '*'
  '@ui-proto/button@*':
    dependencies:
      '@mdx-js/react': '*'
      '@storybook/addon-docs': '*'
      core-js: '*'
  framer-motion@*:
    dependencies:
      csstype: '*'

yarnPath: .yarn/releases/yarn-0.0.1-git.20230302.hash-20c60c4a.cjs
