enableGlobalCache: false

packageExtensions:
  '@storybook/types@*':
    dependencies:
      '@types/react': '*'
  '@storybook/addon-docs@*':
    dependencies:
      '@babel/core': '*'
  '@storybook/components@*':
    dependencies:
      '@storybook/api': '*'
      regenerator-runtime: '*'
  '@testing-library/react@*':
    dependencies:
      react-dom: '*'

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-remote.cjs
