plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-2.4.0.cjs

packageExtensions:
  '@storybook/components@*':
    dependencies:
      'regenerator-runtime': '*'
  '@monstrs/mctl-ui@*':
    dependencies:
      '@monstrs/logger': '*'
  '@ui-parts/design@*':
    dependencies:
      '@storybook/addon-docs': '*'
  '@ui-parts/design-fonts@*':
    dependencies:
      'core-js': '*'
  '@ui-parts/styles@*':
    dependencies:
      'core-js': '*'
  '@ui-parts/button@*':
    dependencies:
      '@storybook/addon-docs': '*'
      '@mdx-js/react': '*'
      'core-js': '*'
  '@ui-proto/button@*':
    dependencies:
      '@storybook/addon-docs': '*'
      '@mdx-js/react': '*'
      'core-js': '*'
  '@ui-admin/button@*':
    dependencies:
      '@storybook/addon-docs': '*'
      '@mdx-js/react': '*'
      'core-js': '*'
  '@ui-admin/theme@*':
    dependencies:
      'core-js': '*'
