packageExtensions:
  '@emotion/styled@*':
    dependencies:
      '@emotion/react': '*'
  '@monstrs/mctl-ui@*':
    dependencies:
      '@monstrs/logger': '*'
  '@storybook/addons@*':
    dependencies:
      '@types/webpack-env': '*'
  '@storybook/components@*':
    dependencies:
      '@emotion/styled-base': '*'
      '@storybook/api': '*'
      regenerator-runtime: '*'
  '@storybook/core@*':
    dependencies:
      '@storybook/builder-webpack5': '*'
  '@storybook/theming@*':
    dependencies:
      '@emotion/serialize': '*'
      '@emotion/utils': '*'
  '@testing-library/react@*':
    dependencies:
      react-dom: '*'
  '@ui-admin/button@*':
    dependencies:
      '@mdx-js/react': '*'
      '@storybook/addon-docs': '*'
      core-js: '*'
  '@ui-admin/theme@*':
    dependencies:
      core-js: '*'
  '@ui-parts/button@*':
    dependencies:
      '@mdx-js/react': '*'
      '@storybook/addon-docs': '*'
      core-js: '*'
  '@ui-parts/design-fonts@*':
    dependencies:
      core-js: '*'
  '@ui-parts/design@*':
    dependencies:
      '@storybook/addon-docs': '*'
  '@ui-parts/styles@*':
    dependencies:
      core-js: '*'
  '@ui-proto/button@*':
    dependencies:
      '@mdx-js/react': '*'
      '@storybook/addon-docs': '*'
      core-js: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - .yarn/plugins/plugin-build-storybook-addons.cjs
  - .yarn/plugins/@monstrs/plugin-essentials.cjs

yarnPath: .yarn/releases/yarn-3.1.0-rc.2.cjs
