apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ui-parts
  namespace: istio-system
spec:
  secretName: ui-parts-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: 'ui-parts.ui.monstrs.dev'
  dnsNames:
    - 'ui-parts.ui.monstrs.dev'
