import { createRainbowSprinkles } from 'rainbow-sprinkles'
import { defineProperties }       from 'rainbow-sprinkles'

const responsiveProperties = defineProperties({
  conditions: {
    mobile: {},
    tablet: { '@media': 'screen and (min-width: 40em)' },
    desktop: { '@media': 'screen and (min-width: 52em)' },
  },
  defaultCondition: 'mobile',
  dynamicProperties: {
    border: true,
    borderRadius: true,
    borderColor: true,
    borderTop: true,
    borderRight: true,
    borderBottom: true,
    borderLeft: true,
    color: true,
    background: true,
    backgroundColor: true,
    opacity: true,
    alignItems: true,
    alignContent: true,
    justifyItems: true,
    justifyContent: true,
    flex: true,
    flexWrap: true,
    flexDirection: true,
    flexGrow: true,
    flexShrink: true,
    flexBasis: true,
    justifySelf: true,
    alignSelf: true,
    order: true,
    display: true,
    width: true,
    height: true,
    minWidth: true,
    minHeight: true,
    maxWidth: true,
    maxHeight: true,
    verticalAlign: true,
    overflow: true,
    overflowX: true,
    overflowY: true,
    boxSizing: true,
    position: true,
    zIndex: true,
    top: true,
    right: true,
    bottom: true,
    left: true,
    boxShadow: true,
    textShadow: true,
    fontFamily: true,
    fontSize: true,
    fontWeight: true,
    lineHeight: true,
    textAlign: true,
    letterSpacing: true,
    fontStyle: true,
    margin: true,
    marginTop: true,
    marginLeft: true,
    marginRight: true,
    marginBottom: true,
    padding: true,
    paddingTop: true,
    paddingLeft: true,
    paddingRight: true,
    paddingBottom: true,
    cursor: true,
    textTransform: true,
    textOverflow: true,
    wordBreak: true,
    whiteSpace: true,
    outline: true,
    transform: true,
    transition: true,
  },
  shorthands: {
    bg: ['backgroundColor'],
    m: ['margin'],
    mr: ['marginRight'],
    ml: ['marginLeft'],
    mt: ['marginTop'],
    mb: ['marginBottom'],
    marginX: ['marginLeft', 'marginRight'],
    marginY: ['marginTop', 'marginBottom'],
    mx: ['marginLeft', 'marginRight'],
    my: ['marginTop', 'marginBottom'],
    p: ['padding'],
    pr: ['paddingRight'],
    pl: ['paddingLeft'],
    pt: ['paddingTop'],
    pb: ['paddingBottom'],
    paddingX: ['paddingLeft', 'paddingRight'],
    paddingY: ['paddingTop', 'paddingBottom'],
    px: ['paddingLeft', 'paddingRight'],
    py: ['paddingTop', 'paddingBottom'],
  },
})

export const sprinkles = createRainbowSprinkles(responsiveProperties)

export type SprinklesProps = Parameters<typeof sprinkles>[0]
